export interface Transaction {
  id: string
  merchant: string
  merchantInitials: string
  merchantColor: string
  reference: string
  date: string
  dateISO: string
  status: 'Completed' | 'Pending' | 'Declined' | 'Refunded'
  category: string
  amount: number
  currency: string
  logoUrl?: string
}

export const transactions: Transaction[] = [
  {
    id: '1',
    merchant: 'Fasthosts',
    merchantInitials: 'FH',
    merchantColor: '#3b82f6',
    reference: '–',
    date: 'Yesterday, 3:59 PM',
    dateISO: '2026-09-14T15:59:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -11.16,
    currency: 'GBP',
  },
  {
    id: '2',
    merchant: 'Tesco',
    merchantInitials: 'T',
    merchantColor: '#e63946',
    reference: '–',
    date: 'Sep 11, 2:21 PM',
    dateISO: '2026-09-11T14:21:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -17.75,
    currency: 'GBP',
  },
  {
    id: '3',
    merchant: 'To Kevin Quirk',
    merchantInitials: 'KQ',
    merchantColor: '#e8c547',
    reference: 'Directors Loan',
    date: 'Sep 10, 3:02 PM',
    dateISO: '2026-09-10T15:02:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -2000,
    currency: 'GBP',
  },
  {
    id: '4',
    merchant: 'To Kevin Quirk',
    merchantInitials: 'KQ',
    merchantColor: '#e8c547',
    reference: 'Directors Loan',
    date: 'Sep 9, 2:31 PM',
    dateISO: '2026-09-09T14:31:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -2000,
    currency: 'GBP',
  },
  {
    id: '5',
    merchant: 'To Kevin Quirk',
    merchantInitials: 'KQ',
    merchantColor: '#e8c547',
    reference: 'Directors Loan',
    date: 'Sep 8, 11:12 AM',
    dateISO: '2026-09-08T11:12:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -3000,
    currency: 'GBP',
  },
  {
    id: '6',
    merchant: 'Fasthosts',
    merchantInitials: 'FH',
    merchantColor: '#3b82f6',
    reference: '–',
    date: 'Sep 8, 9:26 AM',
    dateISO: '2026-09-08T09:26:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -6.14,
    currency: 'GBP',
  },
  {
    id: '7',
    merchant: 'ICO',
    merchantInitials: 'ICO',
    merchantColor: '#2563eb',
    reference: '–',
    date: 'Sep 7, 3:53 PM',
    dateISO: '2026-09-07T15:53:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -52,
    currency: 'GBP',
  },
  {
    id: '8',
    merchant: 'Fasthosts',
    merchantInitials: 'FH',
    merchantColor: '#3b82f6',
    reference: '–',
    date: 'Sep 5, 10:15 AM',
    dateISO: '2026-09-05T10:15:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -5.58,
    currency: 'GBP',
  },
  {
    id: '9',
    merchant: 'Fasthosts',
    merchantInitials: 'FH',
    merchantColor: '#3b82f6',
    reference: '–',
    date: 'Sep 1, 4:13 PM',
    dateISO: '2026-09-01T16:13:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -5.58,
    currency: 'GBP',
  },
  {
    id: '10',
    merchant: 'Costa Coffee',
    merchantInitials: 'CC',
    merchantColor: '#7c3aed',
    reference: '–',
    date: 'Sep 1, 2:27 PM',
    dateISO: '2026-09-01T14:27:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -3.10,
    currency: 'GBP',
  },
  {
    id: '11',
    merchant: 'Costa Coffee',
    merchantInitials: 'CC',
    merchantColor: '#7c3aed',
    reference: '–',
    date: 'Sep 1, 2:09 PM',
    dateISO: '2026-09-01T14:09:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -4.15,
    currency: 'GBP',
  },
  {
    id: '12',
    merchant: 'Tesco',
    merchantInitials: 'T',
    merchantColor: '#e63946',
    reference: '–',
    date: 'Sep 1, 11:50 AM',
    dateISO: '2026-09-01T11:50:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -80,
    currency: 'GBP',
  },
  {
    id: '13',
    merchant: 'The Isle Of Man Steam Pac',
    merchantInitials: 'IOM',
    merchantColor: '#059669',
    reference: '–',
    date: 'Aug 31, 8:30 PM',
    dateISO: '2026-08-31T20:30:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -18.30,
    currency: 'GBP',
  },
  // Additional transactions for the "See all" view
  {
    id: '14',
    merchant: 'Stripe',
    merchantInitials: 'ST',
    merchantColor: '#6366f1',
    reference: 'Payment received',
    date: 'Aug 30, 11:22 AM',
    dateISO: '2026-08-30T11:22:00',
    status: 'Completed',
    category: 'Income',
    amount: 1500,
    currency: 'GBP',
  },
  {
    id: '15',
    merchant: 'Amazon Web Services',
    merchantInitials: 'AWS',
    merchantColor: '#f59e0b',
    reference: 'Invoice #4821',
    date: 'Aug 29, 9:14 AM',
    dateISO: '2026-08-29T09:14:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -92.40,
    currency: 'GBP',
  },
  {
    id: '16',
    merchant: 'Microsoft 365',
    merchantInitials: 'MS',
    merchantColor: '#0284c7',
    reference: 'Subscription',
    date: 'Aug 28, 2:00 PM',
    dateISO: '2026-08-28T14:00:00',
    status: 'Completed',
    category: 'Expenses',
    amount: -12.99,
    currency: 'GBP',
  },
  {
    id: '17',
    merchant: 'Client Payment',
    merchantInitials: 'CP',
    merchantColor: '#10b981',
    reference: 'Project Alpha',
    date: 'Aug 27, 10:30 AM',
    dateISO: '2026-08-27T10:30:00',
    status: 'Completed',
    category: 'Income',
    amount: 3200,
    currency: 'GBP',
  },
]

export const balance = 7416.38
export const currency = 'GBP'
export const accountName = 'Main'
